### PR TITLE
Forgot file

### PR DESCRIPTION
**Pull request by Justman10000**
Forgot file, without the vMenu is not recognized!

### CODE REVIEW

**Comment by TomGrobbe** [comment]
This isn't needed in the source files because it's downloaded by Appveyor whenever an automatic build/release is made. I've purposely left it out because people always get confused and download the source files. If you download the source files and the fxmanifest.lua is in there, people think it's the right files but it's actually not. Hence im not storing it in git.

**Comment by Justman10000** [comment]
Oh, just it wasn't loaded when I compiled the sources!

**Comment by TomGrobbe** [comment]
Yes it's not included in there. You can grab it from a release zip or create your own if you modify the source and rebuild it yourself.

**Comment by Justman10000** [comment]
> 
> 
> Yes it's not included in there. You can grab it from a release zip or create your own if you modify the source and rebuild it yourself.

Yes, well... But it is cumbersome, especially since not everyone thinks about it directly

**Pull request closed without merging**
