### PR TITLE
German added

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by TomGrobbe** [comment]
Thanks, but there is no need to translate the license in multiple languages.

**Comment by Justman10000** [comment]
Yes, only this would be practical, otherwise every German has to translate everything for himself...

**Comment by TomGrobbe** [comment]
Or every German could just learn to speak English, which is an international language?

**Comment by Justman10000** [comment]
Or they could just merge what would be just a few clicks LUUULL 😂

**Pull request closed without merging**
