### PR TITLE
Addon Groups with ACE Permissions (b2802)

### PR DESCRIPTION
**Pull request by Local9**
Covers a request I've kept getting from various communities that have asked in a C# Community Discord I'm in and so I taken the time to work on it and finally PR it here.

Includes all work by @MichaelCoding25 #281 and @XdGoldenTigerOfficial #277 (I wanted to include work from #285 but their fork is 4 commits behind the master so it wouldn't show up on GitHub PR, hopefully I covered most of the items for b2802)

Now back to what I've included, this is due to a request I've been getting for a permissions based grouping system for Addons, I did not change the current addons menu as I didn't want to impact any communities that are still using it and I'm open to improvements in the menus configuration/setup.

The `addon-groups.json` file in the `config` folder allows you to define an ACE permission for a group, e.g. `VehicleSpawner.Staff`. This permission is checked server side and the list of vehicles is returned to the client. Open to PRs on my fork as I'd really like to see vMenu to keep being supported by the FiveM community.

Config only covers `ped` and `vehicle` types currently but only takes a minute to add this in for other menus, hopefully this will add to more features and ideas using ACE Permissions in this way.

Example:
```json
{
  "groups": [
    {
      "permission": "VehicleSpawner.Staff",
      "type": "vehicle",
      "label": "Staff Vehicles",
      "options": [
        {
          "model": "journey2",
          "label": "Journey 2"
        },
        {
          "model": "surfer3",
          "label": "Surfer 3"
        }
      ]
    }
  ]
}
```

File attached contains a working build from my own environment (updated: 2023-02-26 13:33)
[vMenu.zip](https://github.com/TomGrobbe/vMenu/files/10833809/vMenu.zip)

_The reason a lot of files changed is due to Code Cleaning Profiles._

### CODE REVIEW

**Comment by Local9** [comment]
I personally don't understand the AppVeyor error, any guidance on this is welcome.

**Comment by MichaelCoding25** [comment]
> I personally don't understand the AppVeyor error, any guidance on this is welcome.

It means you did not have the README.md file in the folder you were building vMenu from

**Comment by Local9** [comment]
> > I personally don't understand the AppVeyor error, any guidance on this is welcome.
> 
> It means you did not have the README.md file in the folder you were building vMenu from

Thats odd as the build is from a fork of the `master` which has the README.md in the root so that wouldn't make any sense given the error talks about project references, I also do not have control over the AppVeyor settings so I cannot change its settings.

If I go into the error itself, its having issues with project references and mentions the following issue; https://github.com/dotnet/sdk/issues/6688 and is clear in the AppVeyor response;
> Therefore 'Include referenced projects' setting is ignored for .NET Core or .NET Standard projects.

Will see if the reference error is with correct referencing of NewtonSoft but if its MenuAPI then there won't be anything I myself can do.

**Comment by Local9** [comment]
Given I have reverted to the dependency for NewtonSoft v11 instead of using NewtonSoft v12.0.2, reverting the project files will be best, may also just slap all this work in another commit now given the PR has become a mess.

**Pull request closed without merging**
