### PR TITLE
Blood options in player options

### PR DESCRIPTION
**Pull request by aka-lucifer**
• Blood list item for applying different blood & scaring effects.
• Clear blood button to remove all blood & scaring.
• Two permissions for controlling access to these features.

### CODE REVIEW

**Comment by Legacy-TacticalGamingInteractive** [comment]
NICE!

**Comment by Alm0stEthical** [comment]
very nice @TomGrobbe can you take a look?

**Comment by Legacy-TacticalGamingInteractive** [comment]
I dont think Tom is around anymore. Perhaps @XdGoldenTigerOfficial though.

**Comment by XdGoldenTigerOfficial** [comment]
Merged. This seems like a great feature, thank you for your contribution! ❤️

**Pull request merged**
