### PR TITLE
Los Santos Drug Wars add Vehicles 

### PR DESCRIPTION
**Pull request by alebilly**

### CODE REVIEW

**Comment by ryanb9038** [comment]
I have made this FiveM ready for anyone who wants it. This also includes @MichaelCoding25 's additions which you can read about on his pull request. In short, this has every single weapon, ped, and vehicle in the current update version of gta online as of todays date, and Michaels new features; destroy engine, vehicle stance, and low grip tires, all of which came from various other authors which he merged into one asset. 
[vMenu-2802.zip](https://github.com/TomGrobbe/vMenu/files/10830866/vMenu-2802.zip)

**Comment by TayMcKenzieNZ** [comment]
Could you please add the feature for the chameleon paint job?

https://forum.cfx.re/t/how-to-get-the-chameleon-paints/4869883

https://github.com/TomGrobbe/vMenu/pull/277

**Comment by TayMcKenzieNZ** [comment]
> What about new weapons?

They're added.

> , this has every single weapon, ped, and vehicle in the current update version of gta online as of todays date, and Michaels new features; destroy engine, vehicle stance, and low grip tires, all of which came from various other authors which he merged into one asset.
> [vMenu-2802.zip](https://github.com/TomGrobbe/vMenu/files/10830866/vMenu-2802.zip)

**Comment by NinesChaosu** [comment]
WEAPON_PISTOLXM3 is missing and WEAPON_CANDYCANE

**Comment by ryanb9038** [comment]
> WEAPON_PISTOLXM3, WEAPON_ACIDPACKAGE, WEAPON_RAILGUNXM3 is missing and WEAPON_CANDYCANE

Yes, you are correct. I completely overlooked new weapons from the latest update for some reason. I did make sure the 2545/2699 weapons are in though, just overlooked the 2802 weapons.

**Comment by iSentrie** [comment]
> > WEAPON_PISTOLXM3, WEAPON_ACIDPACKAGE, WEAPON_RAILGUNXM3 is missing and WEAPON_CANDYCANE
> 
> Yes, you are correct. I completely overlooked new weapons from the latest update for some reason. I did make sure the 2545/2699 weapons are in though, just overlooked the 2802 weapons.

do u plan to add them?

**Comment by TomGrobbe** [comment]
Took me a bit to figure out if there were any actual new cars after I've merged the other PR, but it seems this one does not include anything new. Therefor I'm closing this PR.

**Pull request closed without merging**
