### PR TITLE
Update vehicles and weapons for The Contract DLC (MPSECURITY, v2545)

### PR DESCRIPTION
**Pull request by MichaelCoding25**
- Add new weapons from DLC
- Add new weapon components from DLC
- Add missing weapon components from older DLCs
- Add new vehicles from DLC

### CODE REVIEW

**Comment by MichaelCoding25** [comment]
Will test this as soon as FiveM starts supporting 2545

**Comment by MichaelCoding25** [comment]
All has been tested and works well, the only thing is the new MP Stun gun has the exact same name and description as the single-player one, the only difference is the damage it does and the reload time.

**Comment by Qiblox** [comment]
> All has been tested and works well, the only thing is the new MP Stun gun has the exact same name and description as the single-player one, the only difference is the damage it does and the reload time.

Don't believe this is true, regular stun-gun uses "weapon_stungun" while the MP one uses "weapon_stungun_mp"

Shouldn't conflict.

**Comment by MichaelCoding25** [comment]
> > All has been tested and works well, the only thing is the new MP Stun gun has the exact same name and description as the single-player one, the only difference is the damage it does and the reload time.
> 
> Don't believe this is true, regular stun-gun uses "weapon_stungun" while the MP one uses "weapon_stungun_mp"
> 
> Shouldn't conflict.

Correct, they don't conflict but if you look in vmenu they have the exact same name, so you can only know which one you get after you spawn it in

**Comment by Qiblox** [comment]
Wouldn't that mean we could just change the name that shows up in the weapon menu to differentiate? Like "Stun Gun 2" or "Stun Gun MP"

**Comment by MichaelCoding25** [comment]
Closing this PR due to #278.

**Pull request closed without merging**
