### PR TITLE
Add new content from The Criminal Enterprises and The Contract DLCs (mpsum2, mpsecurity)

### PR DESCRIPTION
**Pull request by MichaelCoding25**
- Added new vehicles from mpsum2 and mpsecurity DLCs
- Added new weapons from mpsum2 and mpsecurity DLCs
- Added all missing DLC peds
- Added new vehicle stance option (Thanks to #269)
- Added new destroy vehicle engine option (Thanks to #246)
- Add low grip tyres option (Thanks to #269)
- Fixed unlimited ammo description typo
- Updated dependencies to support latest DLC

### CODE REVIEW

**Comment by MichaelCoding25** [comment]
Hey @TomGrobbe, I would love it if you could check this out and merge it if possible.

Thanks in advance.

**Comment by NickReagan** [comment]
> * Added new vehicles from mpsum2 and mpsecurity DLCs
> 
>     * Added new weapons from mpsum2 and mpsecurity DLCs
> 
>     * Added all missing DLC peds
> 
>     * Added new vehicle stance option (Thanks to [Add vehicle stance and drift tires #269](https://github.com/TomGrobbe/vMenu/pull/269))
> 
>     * Added new destroy vehicle engine option (Thanks to [Added a 'destroy engine' button to Vehicle Options. #246](https://github.com/TomGrobbe/vMenu/pull/246))
> 
>     * Add low grip types option (Thanks to [Add vehicle stance and drift tires #269](https://github.com/TomGrobbe/vMenu/pull/269))
> 
>     * Fixed unlimited ammo description typo
> 
>     * Updated dependencies to support latest DLC

@MichaelCoding25 
I am sorry for contacting you through this request but could not find any contact info for you.
How would I be able to add this in my server since it may be awhile before it is merged and a new release is done.
Thanks in advance,
Nick

**Comment by MichaelCoding25** [comment]
@NickReagan https://ci.appveyor.com/project/TomGrobbe/vmenu/builds/44876670/artifacts

**Comment by Sakholway** [comment]
@MichaelCoding25 
Sorry for tag 
How can i  download your version of vMenu ?

**Comment by MichaelCoding25** [comment]
> @MichaelCoding25 
> Sorry for tag 
> How can i  download your version of vMenu ?

I put a link in my last comment

**Comment by Sakholway** [comment]
They say  " The build job does not contain any artifacts."
image

**Comment by MichaelCoding25** [comment]
@Sakholway then unfortunately its not possible unless I push a another commit to it which is not something I have planned.

**Comment by ryanb9038** [comment]
@MichaelCoding25 🥺🥺🥺🥺🥺🥺🥺🥺🥺

**Comment by ryanb9038** [comment]
[vMenu-beta-0b1fae1.zip](https://github.com/TomGrobbe/vMenu/files/10820616/vMenu-beta-0b1fae1.zip)
Here is the compiled and fivem ready version of MichaelCoding25's vMenu. 

Not really sure if there is an issue with me posting this but it seems like he has no interest in ever posting it so I did.

**Comment by ryanb9038** [comment]
[vMenu-MC25.zip](https://github.com/TomGrobbe/vMenu/files/10820919/vMenu-MC25.zip)
I dont know why Mr Michael was not willing to do this himself as it is very easy to do, so I have done it for everyone. This is the FiveM ready download for MichaelCoding25's vMenu fork. You're welcome :3

**Pull request closed without merging**
